VERILOG_SOURCES = $(PWD)/PicoRV32.v
TOPLEVEL = PicoRV32
MODULE = test
# SIM = verilator
# COCOTB_HDL_TIMEPRECISION = 1ns

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim